### ISSUE TITLE
Eslint & prettier

### ISSUE THREAD

**Issue by kamellperry** [Tropix126/sveltekit-package-template#2]
Why have you chosen to not include those things in the project?

**Comment by tropicaaal** [comment]
In general I want to keep the template pretty barebones and leave most of the tooling up to people. Prettier is great, but it's also fundamentally opinionated (that's sort of its thing), and I want to avoid dropping things in like that by default. Guess I could at some point make this into a CLI where people could choose what tooling they wanted, but that's not really a priority of mine at the moment.
